### ISSUE TITLE
feedback modal uses insecure placeholder

### ISSUE THREAD

**Issue by kevincolten** [AustinCodingAcademy/campus-manager#235]

**Comment by zacacollier** [comment]
I haven't had any luck finding API controllers for the feedback modal. If I were to try writing one, I'd probably do so using [express-validator](https://www.npmjs.com/package/express-validator). 

However, it doesn't look like the Feedback form submit even touches the API - it sends POST requests to a separate Google Form API. Any thoughts on how to proceed?
