### ISSUE TITLE
Move auth creds out of link

### ISSUE THREAD

**Issue by kevincolten** [AustinCodingAcademy/campus-manager#265]
Need to remove auth creds out of link

**Comment by kevincolten** [comment]
Maybe put a route in that redirects to correct textbook with auth in headers

**Comment by zacacollier** [comment]
I'm looking into it

**Comment by zacacollier** [comment]
Just submitted a fix in #266

**Comment by kevincolten** [comment]
@zacacollier I like the helper, but we actually need to take it one step farther. Chrome is about to deprecate using the auth creds in the link itself, so we'll need to move the authorization to the headers either on the front end (I don't think we can add headers to an anchor tag) or possibly on a redirect from the backend. We might have to get clever on this one. Worst case scenario is we just put the credentials under the link and have students enter them in manually. I'm not worried about exposing the password, as it can be updated whenever we want.

**Comment by zacacollier** [comment]
Ah I see. Maybe it'd be best to bcrypt a token for the student on login, and pull it from local storage wherever necessary. This solution could apply to more auth use cases than just the Textbook redirect.

**Comment by kevincolten** [comment]
Some links for reference
https://www.chromestatus.com/feature/5669008342777856
https://bugs.chromium.org/p/chromium/issues/detail?id=435547

**Comment by kevincolten** [comment]
Fixed this temporarily by adding
```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/fetch/2.0.3/fetch.min.js"></script>
<script>
  fetch('/_book/gitbook/style.css').catch(error => {
    window.location = window.location.href;
  });
</script>
```
to the headers of the gitbooks.
